version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=customer_management
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d customer_management -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  customer-management-api:
    build: .
    container_name: customer-management-api
    restart: always
    ports:
      - '3333:3333'
    environment:
      - DATABASE_URL=postgresql://postgres:docker@postgres:5432/customer_management
      - HOST=0.0.0.0
      - PORT=3333
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data: