version: '3.7'

services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=customer_management
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: